project:
  type: website

website:
  title: "Epiverse-TRACE Third Annual Summit 2024"
  navbar:
    background: secondary
    search: true
    pinned: true
    left:
        - text: "Programme"
          href: schedule.qmd
        - text: "Pre-summit Training"
          href: pre-training.qmd
        - text: "Travel Information"
          menu: 
            - text: "Venue"
              icon: "luggage"
              href: venue.qmd
            - text: "Travel & Visas"
              icon: "passport"
              href: visa.qmd
            - text: Accommodation
              icon: "buildings"
              href: accommodation.qmd
        - text: "Committees"
          href: committees.qmd
        - text: "Contact Us"
          href: contact.qmd

  page-footer:
    border: true
    background: light
    center: |
      [![](./images/LogoDataDotOrg.png){fig-alt="datadotorg" width=80px}](https://data.org/a)
      [![](./images/idrc_logo.png){fig-alt="IDRC" width=200px}](https://www.idrc-crdi.ca/en)
      [![](./images/lshtm-logo.png){fig-alt="LSHTM" width=125px}](https://www.lshtm.ac.uk/)
      [![](./images/UKRI_MRCG_LSHTM_logo.png){fig-alt="MRCG" width=200px}](https://www.lshtm.ac.uk/research/units/mrc-gambia)
      [![](./images/Uniandes.png){fig-alt="uniandes" width=100px}](https://uniandes.edu.co/)
      [![](./images/Javeriana.png){fig-alt="javeriana" width=80px}](https://javeriana.edu.co/)
    right:
      - icon: github
        href: https://github.com/epiverse-trace
      - icon: twitter
        href: https://twitter.com/Epiverse_TRACE
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 2
    toc-location: left

editor: visual

